export const SearchQueryLabel = "Keyword";
export const SearchUrlLabel = "Url";
export const BtnSearchLabel = "Search";
export const SearchEngineHeader = "Search Engine";
export const TotalHeader = "Total";
export const PositionHeader = "Positions";
export const MessageTitle = "Oops! Something went wrong.";
export const MessageContent = "We encountered an issue while fetching the SEO analysis. Please try again later or contact support center if the problem persists.";
export const BtnCloseLabel = "Close";